name: 'auto-tag'
description: 'Create a new git-tag'
inputs:
  tag:
    description: 'The tag to potentially create'
    required: true
  gh_token:
    description: 'The token to use in order to push the tag'
    required: true
outputs:
  status:
    description: "skip or create"
    value: ${{ steps.status.outputs.status }}
runs:
  using: "composite"
  steps:
  - name: "Check if ${{ inputs.tag }} exists"
    shell: bash
    id: status
    env:
      TAG: ${{ inputs.tag }}
    run: |
      if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
        echo "Tag ${TAG} exists"
        echo "status=skip" >> $GITHUB_OUTPUT
      else
        echo "Tag ${TAG} does not exist"
        echo "status=create" >> $GITHUB_OUTPUT
      fi
  - name: "Push tag"
    shell: bash
    env:
      TAG: ${{ inputs.TAG }}
      USER: ${{ inputs.user }}
    if: steps.status.outputs.status == 'create'
    run: |
      git config --local user.email "till@php.net"
      git config --local user.name "runway-ci-bot[bot]"
      git tag -a ${TAG} -m "auto-tag: ${TAG}"
      git push https://x-access-token:${{ inputs.gh_token }}@github.com/${{ github.repository }} "$TAG"

