name: rebuild

on:
  workflow_dispatch:
    inputs:
      hugo-version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: refs/tags/${{ inputs.hugo-version }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
      with:
        images: ghcr.io/${{ github.repository }}
        tags: type=semver,pattern={{raw}},value=${{ inputs.hugo-version }}
    - uses: docker/build-push-action@v5
      with:
        build-args: ${{ inputs.hugo-version }}
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
